Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2021-12, with the labels that each got.

#119 support alibaba cloud ccm
  manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
  pkg/cloud/alibaba/alibaba.go
  pkg/cloud/alibaba/alibaba_test.go
  pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/config/config.go
Labels: ok-to-test, approved, lgtm

#151 Alibaba Cloud Provider: fix the path to the binary to match the build…
  pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml
Labels: approved, lgtm

#138 [release-4.9] Bug 2015503: User CA bundle sync controller
  Dockerfile
  Makefile
  cmd/config-sync-controllers/main.go
  docs/dev/cloud-config-sync.md
  docs/dev/trusted_ca_bundle_sync.md
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/openstack/assets/deployment.yaml
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/common_consts.go
  pkg/controllers/fixtures/additional_ca_amazon.pem
  pkg/controllers/fixtures/additional_ca_ms.pem
  pkg/controllers/fixtures/trust_bundle_invalid.pem
  pkg/controllers/fixtures/trust_bundle_valid.pem
  pkg/controllers/trusted_ca_bundle_controller.go
  pkg/controllers/trusted_ca_bundle_controller_test.go
  pkg/controllers/watch_predicates.go
  pkg/util/trustbundle.go
Labels: cherry-pick-approved, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved, backport-risk-assessed

#153 Skip cloud-config sync on aws platform
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: approved, lgtm

#152 [OCPCLOUD-1307] Refactor CCCMO cluster-operator resource handling
  cmd/cluster-cloud-controller-manager-operator/main.go
  cmd/config-sync-controllers/main.go
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/clusteroperator_controller_test.go
  pkg/controllers/status.go
  pkg/controllers/status_test.go
  pkg/controllers/trusted_ca_bundle_controller.go
  pkg/controllers/trusted_ca_bundle_controller_test.go
Labels: approved, lgtm

#156 Bug 2033489: allow baremetal platform to skip syncing
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug

#158 Bug 2033489: Use a list of platforms where config sync is required
  pkg/controllers/cloud_config_sync_controller.go
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug

#157 Bug 2028054: Ensure old deployment is deleted before new deployment creation
  manifests/0000_26_cloud-controller-manager-operator_10_deployment_tombstone.yaml
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#154 Bug 2032926: Bump envtest version
  Makefile
  hack/unit-tests.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#159 Bug 2032926: Fix CA bundle tests to use async assertions correctly
  pkg/controllers/trusted_ca_bundle_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#160 Bug 2032926: Fix config sync tests to use async assertions correctly
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
