Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2021-11, with the labels that each got.

#140 Bug 2017565: [OCPCLOUD-1306] Add user defined trusted CA from cloud-config to ccm-trusted-ca bundle
  docs/dev/trusted_ca_bundle_sync.md
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
  pkg/controllers/common_consts.go
  pkg/controllers/trusted_ca_bundle_controller.go
  pkg/controllers/trusted_ca_bundle_controller_test.go
  pkg/controllers/watch_predicates.go
  pkg/util/trustbundle.go
Labels: bugzilla/severity-medium, approved, lgtm, bugzilla/valid-bug

#129 Powervs support
  pkg/cloud/cloud.go
Labels: approved, lgtm

#143 Remove invalid feature-gate option from ccm deployment
  pkg/cloud/ibm/assets/deployment.yaml
Labels: approved, lgtm

#142 Bump library-go for support Power VS out-of-tree cloud providers
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/modules.txt
Labels: approved, lgtm

#145 Remove unused PersistentVolume RBAC
  manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml
Labels: approved, lgtm

#147 [Bug 2019219] IBMCloud: Add RG IAM permissions
  manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml
Labels: approved, lgtm

#148 Added enablePublicEndpoint environmental variable to IBM Cloud deployment file
  pkg/cloud/ibm/assets/deployment.yaml
  pkg/cloud/ibm/ibm.go
Labels: approved, lgtm

#131 Add GCP CCM support
  manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
  manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-gcp.yaml
  manifests/image-references
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/gcp/assets/cloud-controller-manager.yaml
  pkg/cloud/gcp/gcp.go
  pkg/cloud/gcp/gcp_test.go
  pkg/config/config.go
Labels: approved, lgtm

#149 Update documentation
  README.md
  docs/dev/azure-config-credentials-injector.md
  docs/dev/hacking-guide.md
  docs/dev/trusted_ca_bundle_sync.md
Labels: approved, lgtm

#139 Get rid of server-side apply
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/clusteroperator_controller_test.go
  pkg/controllers/resourceapply/resourceapply.go
  pkg/controllers/resourceapply/resourceapply_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/modules.txt
Labels: approved, lgtm

#130 Vsphere ccm support
  manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
  manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-vsphere.yaml
  manifests/image-references
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/vsphere/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/vsphere/vsphere.go
  pkg/cloud/vsphere/vsphere_test.go
  pkg/config/config.go
Labels: approved, lgtm

#150 Bug 2025884: Inject openstack CCM image within deployment template
  pkg/cloud/openstack/assets/deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
