Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2021-08, with the labels that each got.

#101 Bug 1985366: Use registered ports and ensure that ports are defined in pod specs
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/openstack/assets/deployment.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#103 Bug 1990075: add maxUnavailable parameter to daemon set pods for azure
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
Labels: bugzilla/severity-medium, approved, lgtm, bugzilla/valid-bug

#106 Bug 1993087: cloud-config Azure credentials injector
  Dockerfile
  Makefile
  cmd/azure-config-credentials-injector/credentials_injector_test.go
  cmd/azure-config-credentials-injector/main.go
  docs/dev/azure-config-credentials-injector.md
  go.mod
  go.sum
  manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
  manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/fixtures/images.json
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#111 Bug 1999018: Ensure rollingUpdate strategy is cleared to allow upgrades
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
