Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2021-09, with the labels that each got.

#114 Bug 2000191: Ensure CCCMO and CCMs adheres to OpenShift recommended leader election
  cmd/cloud-config-sync-controller/main.go
  cmd/cluster-cloud-controller-manager-operator/main.go
  go.mod
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/openstack/assets/deployment.yaml
  pkg/util/durations.go
  vendor/k8s.io/component-base/config/options/leaderelectionconfig.go
  vendor/modules.txt
Labels: bugzilla/severity-medium, approved, lgtm, bugzilla/valid-bug

#116 Bug 1998466: Fix deployment strategy typo
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug

#97 Add initial ibm pkg assets and embed files
  manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/ibm/assets/deployment.yaml
  pkg/cloud/ibm/ibm.go
  pkg/cloud/ibm/ibm_test.go
Labels: approved, lgtm

#100 Allow CCMs to get services and configmaps
  manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml
Labels: approved, lgtm

#118 Vendor: update library-go for ibmcloud provider
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/modules.txt
Labels: approved, lgtm

#105 Add support for IBM images
  manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
  manifests/image-references
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, lgtm

#121 Remove duplicated platform list in cloud tests
  pkg/cloud/cloud_test.go
Labels: approved, lgtm

#120 Bug 2001825: Enforce the cloud-route controller disabled across platforms
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/ibm/assets/deployment.yaml
  pkg/cloud/openstack/assets/deployment.yaml
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug

#123 Update OWNERS
  OWNERS
  pkg/cloud/openstack/OWNERS
Labels: approved, lgtm

#112 Update readme. Add links to CCMs repos.
  README.md
Labels: approved, lgtm

#122 Unify pre-provisioning checks in a single location
  pkg/controllers/clusteroperator_controller.go
Labels: approved, lgtm

#124 Check diff after generate and vendor tasks
  Makefile
  hack/verify-diff.sh
Labels: approved, lgtm

#128 Bug 2004924: Enforce the cloud-route controller disabled across platforms
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/openstack/assets/deployment.yaml
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug, staff-eng-approved

#110 OCPCLOUD-1189: Move cloud provider specific logic behind interface
  go.mod
  go.sum
  hack/unit-tests.sh
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/aws/aws.go
  pkg/cloud/aws/aws_test.go
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azurestack/azurestack.go
  pkg/cloud/azurestack/azurestack_test.go
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/common/_testdata/assets/deployment.yaml
  pkg/cloud/common/interfaces.go
  pkg/cloud/common/sources.go
  pkg/cloud/common/sources_test.go
  pkg/cloud/common/substitution.go
  pkg/cloud/common/substitution_test.go
  pkg/cloud/common/templates.go
  pkg/cloud/common/templates_test.go
  pkg/cloud/errors.go
  pkg/cloud/ibm/assets/deployment.yaml
  pkg/cloud/ibm/ibm.go
  pkg/cloud/ibm/ibm_test.go
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/clusteroperator_controller_test.go
  pkg/controllers/fixtures/images.json
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
  pkg/util/testingutils/logging.go
  vendor/github.com/asaskevich/govalidator/.gitignore
  vendor/github.com/asaskevich/govalidator/.travis.yml
  vendor/github.com/asaskevich/govalidator/CODE_OF_CONDUCT.md
  vendor/github.com/asaskevich/govalidator/CONTRIBUTING.md
  vendor/github.com/asaskevich/govalidator/LICENSE
  vendor/github.com/asaskevich/govalidator/README.md
  vendor/github.com/asaskevich/govalidator/arrays.go
  vendor/github.com/asaskevich/govalidator/converter.go
  vendor/github.com/asaskevich/govalidator/doc.go
  vendor/github.com/asaskevich/govalidator/error.go
  vendor/github.com/asaskevich/govalidator/go.mod
  vendor/github.com/asaskevich/govalidator/numerics.go
  vendor/github.com/asaskevich/govalidator/patterns.go
  vendor/github.com/asaskevich/govalidator/types.go
  vendor/github.com/asaskevich/govalidator/utils.go
  vendor/github.com/asaskevich/govalidator/validator.go
  vendor/github.com/asaskevich/govalidator/wercker.yml
  vendor/modules.txt
Labels: approved, lgtm

#132 Fix "vendor" job
  go.mod
Labels: approved, lgtm
