Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2022-04, with the labels that each got.

#177 Add a troubleshooting doc
  docs/user/troubleshooting.md
Labels: approved, lgtm

#174 Bug 2051457: CCM PodDisruptionBudgets
  manifests/0000_26_cloud-controller-manager-operator_17_credentialsrequest-vsphere.yaml
  pkg/cloud/alibaba/alibaba.go
  pkg/cloud/alibaba/alibaba_test.go
  pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/aws/assets/deployment.yaml
  pkg/cloud/aws/aws.go
  pkg/cloud/aws/aws_test.go
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azurestack/azurestack.go
  pkg/cloud/azurestack/azurestack_test.go
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/common/resources.go
  pkg/cloud/gcp/assets/cloud-controller-manager.yaml
  pkg/cloud/gcp/gcp.go
  pkg/cloud/gcp/gcp_test.go
  pkg/cloud/ibm/assets/deployment.yaml
  pkg/cloud/ibm/ibm.go
  pkg/cloud/ibm/ibm_test.go
  pkg/cloud/openstack/assets/deployment.yaml
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
  pkg/cloud/powervs/assets/deployment.yaml
  pkg/cloud/powervs/powervs.go
  pkg/cloud/powervs/powervs_test.go
  pkg/cloud/vsphere/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/vsphere/vsphere.go
  pkg/cloud/vsphere/vsphere_test.go
  pkg/config/config.go
  pkg/controllers/clusteroperator_controller_test.go
  pkg/controllers/resourceapply/resourceapply.go
  pkg/controllers/resourceapply/resourceapply_test.go
Labels: bugzilla/severity-medium, approved, lgtm, bugzilla/valid-bug

#185 OpenStack: ensure config-map is updated only when needed
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
Labels: approved, lgtm

#184 Bug 2074606: Allow OpenStack CCM to annotate Service objects
  manifests/0000_26_cloud-controller-manager-operator_04_rbac_provider_openstack.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
