Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2022-05, with the labels that each got.

#187 Bug 2079791: Ensure release version is injected into all controller status clients
  cmd/cluster-cloud-controller-manager-operator/main.go
  cmd/config-sync-controllers/main.go
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
  pkg/controllers/status.go
Labels: cherry-pick-approved, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backport-risk-assessed

#188 Remove port argument and update enivronment variable name from powervs cloud provider deployment
  pkg/cloud/powervs/assets/deployment.yaml
Labels: approved, lgtm

#180 [release-4.9] Bug 2064837: Fix CCCMO metric ports configuration
  cmd/config-sync-controllers/main.go
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: cherry-pick-approved, bugzilla/severity-medium, approved, lgtm, bugzilla/valid-bug, backport-risk-assessed

#189 Bug 2082687: IBMCloud: Remove CCM port argument
  pkg/cloud/ibm/assets/deployment.yaml
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug

#193 [OCPCLOUD-1541] Bug 2089334: Use service account credentials for all providers
  pkg/cloud/cloud_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
