Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2022-02, with the labels that each got.

#167 Bug 2047998: Alibaba should deploy image from release payload
  manifests/image-references
  pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug

#168 Bug 2048478: [release-4.10] Alibaba should deploy image from release payload
  manifests/image-references
  pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml
Labels: bugzilla/severity-urgent, approved, lgtm, bugzilla/valid-bug, staff-eng-approved

#169 Fix a typo in watch predicates
  pkg/controllers/watch_predicates.go
Labels: approved, lgtm

#170 Update OWNERS
  pkg/cloud/openstack/OWNERS
Labels: approved, lgtm

#173 Bug 2055723: start watching KubeControllerManager resource
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/watch_predicates.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
