Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2023-11, with the labels that each got.

#292 OSASINFRA-3284: Add Events to OpenStack's RBAC
  manifests/0000_26_cloud-controller-manager-operator_04_rbac_provider_openstack.yaml
Labels: approved, lgtm, jira/valid-reference

#294 OSASINFRA-3289: OpenStack: Remove Kuryr bits
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#299 OCPBUGS-23308: Set IPFamilyPriority and ExcludeNetworkSubnetCIDR for vSphere IPv6-only
  pkg/cloud/vsphere/vsphere_config_transformer.go
  pkg/cloud/vsphere/vsphere_config_transformer_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#301 OCPCLOUD-2278: Add kube-rbac-proxy container & ensure metrics are only available via HTTPS
  manifests/0000_26_cloud-controller-manager-operator_05_metrics-service.yaml
  manifests/0000_26_cloud-controller-manager-operator_06_kube-rbac-proxy-config.yaml
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#303 TRT-1374: Revert #301 "OCPCLOUD-2278: Add kube-rbac-proxy container & ensure metrics are only available via HTTPS"
  manifests/0000_26_cloud-controller-manager-operator_05_metrics-service.yaml
  manifests/0000_26_cloud-controller-manager-operator_06_kube-rbac-proxy-config.yaml
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: approved, lgtm, jira/valid-reference
