Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2023-12, with the labels that each got.

#305 TRT-1378: Revert #304 "Undo TRT-1374: Revert for \"OCPCLOUD-2278: Add kube-rbac-proxy container & ensure metrics are only available via HTTPS\""
  manifests/0000_26_cloud-controller-manager-operator_05_metrics-service.yaml
  manifests/0000_26_cloud-controller-manager-operator_06_kube-rbac-proxy-config.yaml
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#306 Undo TRT-1378: Revert for "OCPCLOUD-2278: Add kube-rbac-proxy container & ensure metrics are only available via HTTPS"
  manifests/0000_26_cloud-controller-manager-operator_05_metrics-service.yaml
  manifests/0000_26_cloud-controller-manager-operator_06_kube-rbac-proxy-config.yaml
  manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
  manifests/image-references
Labels: approved, lgtm, jira/valid-reference

#293 OCPVE-788: annotate credentials request manifests
  manifests/0000_26_cloud-controller-manager-operator_13_credentialsrequest-openstack.yaml
  manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
  manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml
  manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-powervs.yaml
  manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-gcp.yaml
  manifests/0000_26_cloud-controller-manager-operator_17_credentialsrequest-vsphere.yaml
  manifests/0000_26_cloud-controller-manager-operator_18_credentialsrequest-nutanix.yaml
Labels: approved, lgtm, jira/valid-reference

#307 trt-1382: test add space
  README.md
Labels: approved, lgtm, jira/valid-reference

#309 trt-1382: reorder flag initialization
  README.md
  cmd/cluster-cloud-controller-manager-operator/main.go
Labels: approved, lgtm, jira/valid-reference

#205 OCPCLOUD-1724: GCP Credentials req. manifest of CCMO to use new API field
  manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-gcp.yaml
Labels: approved, lgtm, lifecycle/rotten, jira/valid-reference

#310 OCPBUGS-5825: Adds GCP ClusterRole and ClusterRoleBinding
  manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/gcp/assets/gcp-cloud-controller-manager-clusterrole.yaml
  pkg/cloud/gcp/assets/gcp-cloud-controller-manager-clusterrolebinding.yaml
  pkg/cloud/gcp/gcp.go
  pkg/cloud/gcp/gcp_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#313 OCPBUGS-25750: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
