Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2023-04, with the labels that each got.

#239 OCPBUGS-7898: add a check for nutanix cloud conf map
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/status.go
Labels: cherry-pick-approved, approved, lgtm, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#242 Revert azure out of tree provider change
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/modules.txt
Labels: approved, lgtm

#240 OCPBUGS-11284: Add beta topology labels flag to Azure cloud node manager
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/valid-reference
