Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2023-07, with the labels that each got.

#257 OCPBUGS-14425: Alibaba platforms should not be upgreadable
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/status.go
  pkg/controllers/status_test.go
  pkg/controllers/trusted_ca_bundle_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#260 OCPBUGS-15746: Alibaba platforms should not be upgradeable
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/status.go
  pkg/controllers/status_test.go
  pkg/controllers/trusted_ca_bundle_controller.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#267 OCPBUGS-16690: Allow all NoSchedule taints for Azure CNM DaemonSet
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/cloud_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#263 OpenStack: Set max-shared-lb to disable the feature
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
Labels: approved, lgtm

#266 OpenStack: Extend owners
  pkg/cloud/openstack/OWNERS
Labels: approved, lgtm
