Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2023-03, with the labels that each got.

#228 [release-4.12] OCPBUGS-7884: Restart pods if related configuration was changed
  pkg/controllers/clusteroperator_controller.go
  pkg/controllers/clusteroperator_controller_test.go
  pkg/controllers/resourceapply/config_hash.go
  pkg/controllers/resourceapply/config_hash_test.go
  pkg/controllers/resourceapply/resourceapply.go
  pkg/controllers/resourceapply/resourceapply_test.go
Labels: cherry-pick-approved, approved, lgtm, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#230 OCPCLOUD-1779: Prevent operator to provision operands if platform is set to 'External'
  pkg/controllers/clusteroperator_controller.go
Labels: approved, lgtm, jira/valid-reference

#236 OCPBUGS-8530: add rbac permission for Nutanix CCM manager
  manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml
  pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#234 Reset library-go to openshift fork
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#233 OCPCLOUD-1779, OCPBUGS-8694: Set missed operator status in case of the 'External' platform type encountered
  pkg/controllers/clusteroperator_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
