Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2023-08, with the labels that each got.

#269 OCPBUGS-17101: update x/net dependency to 0.7.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/language/language.go
  vendor/modules.txt
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#264 OpenStack: Enable manage-security-groups by default
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
Labels: approved, lgtm

#259 OCPBUGS-15154: Prune provider permissions post move to use-service-account-credentials
  cmd/cluster-cloud-controller-manager-operator/main.go
  manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
  manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml
  pkg/cloud/cloud_test.go
  pkg/cloud/common/substitution.go
  pkg/cloud/common/substitution_test.go
  pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/nutanix/assets/nutanix-cloud-controller-manager-clusterrole.yaml
  pkg/cloud/nutanix/assets/nutanix-cloud-controller-manager-clusterrolebinding.yaml
  pkg/cloud/nutanix/assets/nutanix-cloud-controller-manager-role.yaml
  pkg/cloud/nutanix/assets/nutanix-cloud-controller-manager-rolebinding.yaml
  pkg/cloud/nutanix/nutanix.go
  pkg/cloud/nutanix/nutanix_test.go
  pkg/cloud/vsphere/assets/cloud-controller-manager-clusterrolebinding.yaml
  pkg/cloud/vsphere/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/vsphere/assets/cloud-controller-manager-rolebinding.yaml
  pkg/cloud/vsphere/assets/vsphere-cloud-controller-manager-clusterrole.yaml
  pkg/cloud/vsphere/assets/vsphere-cloud-controller-manager-clusterrolebinding.yaml
  pkg/cloud/vsphere/assets/vsphere-cloud-controller-manager-role.yaml
  pkg/cloud/vsphere/assets/vsphere-cloud-controller-manager-rolebinding.yaml
  pkg/cloud/vsphere/vsphere.go
  pkg/cloud/vsphere/vsphere_test.go
  pkg/controllers/resourceapply/resourceapply.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#268 OCPCLOUD-2149: Azure: CCM and node manager to use provided credentials instead of MSI.
  cmd/azure-config-credentials-injector/credentials_injector_test.go
  cmd/azure-config-credentials-injector/main.go
  manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/cloud_test.go
Labels: approved, lgtm, jira/valid-reference

#274 OCPCLOUD-2013: Move Azure Credentials Request to custom role
  manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference
