Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2024-06, with the labels that each got.

#348 OCPBUGS-34689: Nutanix CCM pods Cipher Suites vulnerability issue
  pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#345 NO-JIRA: openstack: Remove dulek from OWNERS
  pkg/cloud/openstack/OWNERS
Labels: approved, lgtm, jira/valid-reference

#354 OCPBUGS-35562: update unit tests [release-4.13]
  pkg/cloud/cloud_test.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#357 NO-JIRA: Update OWNERS
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#355 OCPBUGS-35798: PowerVS: Remove bind address
  pkg/cloud/powervs/assets/deployment.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
