Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2024-01, with the labels that each got.

#316 OCPBUGS-25483: Adds CloudConfigTransformer for Azure
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/cloud.go
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#319 [release-4.15] OCPBUGS-26210: Adds CloudConfigTransformer for Azure
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/cloud.go
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#322 OCPBUGS-26494: PowerVS: handle 4.16 changes
  pkg/cloud/powervs/assets/deployment.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#323 OCPBUGS-25887: IBMCloud: Patch CCM for 4.16
  pkg/cloud/ibm/assets/deployment.yaml
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#314 OCPBUGS-25751: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#327 NO-JIRA:Use expressive Gomega matchers with Eventually
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: approved, lgtm, jira/valid-reference
