Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2025-02, with the labels that each got.

#384 OCPCLOUD-2843: AWS CCM should be configured with the AWS cloud provider config
  pkg/cloud/aws/assets/deployment.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#379 OCPBUGS-48481: annotation validation policy
  pkg/cloud/azure/assets/validating-admission-service-annotation-policy-binding.yaml
  pkg/cloud/azure/assets/validating-admission-service-annotation-policy.yaml
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/cloud_test.go
  pkg/cloud/gcp/assets/validating-admission-policy-binding.yaml
  pkg/cloud/gcp/assets/validating-admission-policy.yaml
  pkg/cloud/gcp/gcp.go
  pkg/cloud/gcp/gcp_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#385 OCPBUGS-41827: update injector to support secret as well
  cmd/azure-config-credentials-injector/credentials_injector_test.go
  cmd/azure-config-credentials-injector/main.go
  pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
  pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
  pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference
