Repository openshift/cluster-cloud-controller-manager-operator, pull requests merged in 2025-09, with the labels that each got.

#411 [release-4.16] OCPBUGS-60387: Add Service using common resource templating
  pkg/cloud/cloud_test.go
  pkg/cloud/common/resources.go
  pkg/controllers/clusteroperator_controller_test.go
  pkg/controllers/resourceapply/resourceapply.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#400 SPLAT-2341: Add feature gate support in the cloud-config sync controller
  cmd/config-sync-controllers/main.go
  pkg/cloud/aws/aws_config_transformer.go
  pkg/cloud/aws/aws_config_transformer_test.go
  pkg/cloud/azure/azure.go
  pkg/cloud/azure/azure_test.go
  pkg/cloud/azurestack/azurestack.go
  pkg/cloud/azurestack/azurestack_test.go
  pkg/cloud/cloud.go
  pkg/cloud/common/config.go
  pkg/cloud/openstack/openstack.go
  pkg/cloud/openstack/openstack_test.go
  pkg/cloud/vsphere/vsphere_config_transformer.go
  pkg/cloud/vsphere/vsphere_config_transformer_test.go
  pkg/controllers/cloud_config_sync_controller.go
  pkg/controllers/cloud_config_sync_controller_test.go
Labels: approved, lgtm, jira/valid-reference, verified

#417 OCPBUGS-54490: Add Azure permissions for Private Link Service operations
  manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified

#416 OCPBUGS-60385: Add Microsoft.Network/publicIPAddresses/delete permission
  manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified
